config/routes.rb
Rails.application.routes.draw do
  resources :patients, only: [:new, :create]
  resources :doctors, only: [:new, :create]
  resources :appointments, only: [:index, :new, :create]
  devise_for :users, controllers: {
        omniauth_callbacks: 'callbacks',
        sessions: 'users/sessions'
      }
  root 'appointments#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  validates :name, presence: true
  validates :phone_no, uniqueness: true
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to appointments_url, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { redirect_to appointments_url }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :phone_no)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.slim
= simple_form_for(@patient) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :phone_no

  .form-actions
    = f.button :submit

app/views/patients/edit.html.slim
h1 Editing patient

== render 'form'

= link_to 'Show', @patient
'  |
= link_to 'Back', patients_path

app/views/patients/index.html.slim
h1 Listing patients

table
  thead
    tr
      th Name
      th Phone no
      th
      th
      th

  tbody
    - @patients.each do |patient|
      tr
        td = patient.name
        td = patient.phone_no
        td = link_to 'Show', patient
        td = link_to 'Edit', edit_patient_path(patient)
        td = link_to 'Destroy', patient, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Patient', new_patient_path

app/views/patients/new.html.slim
h1 New patient

== render 'form'

= link_to 'Back', patients_path

app/views/patients/show.html.slim
p#notice = notice

p
  strong Name:
  = @patient.name
p
  strong Phone no:
  = @patient.phone_no

= link_to 'Edit', edit_patient_path(@patient)
'  |
= link_to 'Back', patients_path