config/routes.rb
Rails.application.routes.draw do
  resources :patients, only: [:new, :create]
  resources :doctors, only: [:new, :create]
  resources :appointments, only: [:index, :new, :create]
  devise_for :users, controllers: {
        omniauth_callbacks: 'callbacks',
        sessions: 'users/sessions'
      }
  root 'appointments#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  validates :name, presence: true
  validates :phone_no, uniqueness: true
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to appointments_url, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { redirect_to appointments_url }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :phone_no, :specialization)
    end
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.slim
= simple_form_for(@doctor) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :phone_no
    = f.input :specialization

  .form-actions
    = f.button :submit

app/views/doctors/edit.html.slim
h1 Editing doctor

== render 'form'

= link_to 'Show', @doctor
'  |
= link_to 'Back', doctors_path

app/views/doctors/index.html.slim
h1 Listing doctors

table
  thead
    tr
      th Name
      th Phone no
      th Specialization
      th
      th
      th

  tbody
    - @doctors.each do |doctor|
      tr
        td = doctor.name
        td = doctor.phone_no
        td = doctor.specialization
        td = link_to 'Show', doctor
        td = link_to 'Edit', edit_doctor_path(doctor)
        td = link_to 'Destroy', doctor, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Doctor', new_doctor_path

app/views/doctors/new.html.slim
h1 New doctor

== render 'form'

= link_to 'Back', doctors_path

app/views/doctors/show.html.slim
p#notice = notice

p
  strong Name:
  = @doctor.name
p
  strong Phone no:
  = @doctor.phone_no
p
  strong Specialization:
  = @doctor.specialization

= link_to 'Edit', edit_doctor_path(@doctor)
'  |
= link_to 'Back', doctors_path