config/routes.rb
Rails.application.routes.draw do
  resources :patients, only: [:new, :create]
  resources :doctors, only: [:new, :create]
  resources :appointments, only: [:index, :new, :create]
  devise_for :users, controllers: {
        omniauth_callbacks: 'callbacks',
        sessions: 'users/sessions'
      }
  root 'appointments#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
    @appointment = Appointment.new
    @patient = Patient.new
    @doctor = Doctor.new
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointments_url, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { redirect_to appointments_url }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointments_url, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:patient_id, :doctor_id, :disease)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.slim
.content
  .head Appointment
  .hr
  .form
    = simple_form_for @appointment do |f|
      = f.association :doctor, collection: Doctor.order(:name), prompt: "Doctor name", input_html: { class: 'form-control'}, label: false
      = f.association :patient, collection: Patient.order(:name), prompt: "Patient name", input_html: { class: 'form-control'}, label: false
      = f.input :disease, input_html: { class: 'form-control', placeholder: 'Disease' }, label: false
      = f.button :submit, 'Submit', class: 'btn-submit appointment-submit'
  #notice
    - if notice.present?
      - note = notice.downcase
      - if "appointment".in? note
        = notice

app/views/appointments/_doctor.html.slim
.content
  .head Doctor
  .hr
  .form
    = simple_form_for @doctor do |f|
      = f.input :name, input_html: { class: 'form-control', placeholder: 'Name' }, label: false
      = f.input :phone_no, input_html: { class: 'form-control', placeholder: 'Phone no' }, label: false
      = f.input :specialization, input_html: { class: 'form-control', placeholder: 'Specialization' }, label: false
      = f.button :submit, 'Submit', class: 'btn-submit doctor-submit'
  #notice
    - if notice.present?
      - note = notice.downcase
      - if "doctor".in? note
        = notice

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.number_field :patient_id, id: :appointment_patient_id %>
  </div>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.number_field :doctor_id, id: :appointment_doctor_id %>
  </div>

  <div class="field">
    <%= form.label :disease %>
    <%= form.text_field :disease, id: :appointment_disease %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/_patient.html.slim
.content
  .head Patient
  .hr
  .form
    = simple_form_for @patient do |f|
      = f.input :name, input_html: { class: 'form-control', placeholder: 'Name' }, label: false
      = f.input :phone_no, input_html: { class: 'form-control', placeholder: 'Phone no' }, label: false
      = f.button :submit, 'Submit', class: 'btn-submit patient-submit'
  #notice
    - if notice.present?
      - note = notice.downcase
      - if "patient".in? note
        = notice

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.slim
.flex-box
  .flex-item
    = render 'patient'
  .flex-item
    = render 'doctor'
  .flex-item
    = render 'appointment'
  .flex-item
    .content.content-last
      .head View appointments
      .hr
      - if @appointments.present?
        table.ap-table
          tr
            th Patient
            th Doctor
            th Disease
          - @appointments.each do |appointment|
            tr
              td
                = appointment.patient.name
              td
                = appointment.doctor.name
              td
                = appointment.disease
      - else
        .text-center.mt30
          h4 No appointments made yet.

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient_id %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor_id %>
</p>

<p>
  <strong>Disease:</strong>
  <%= @appointment.disease %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>